var gl=[{"topic":"Week 1: ","subtopics":[{"name":"Title","fullname":"Title title","audio":"1-1.mp3","img":"1-1.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"1-2.mp3","img":"1-2.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"1-3.mp3","img":"1-3.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"1-4.mp3","img":"1-4.jpg","points":["Point 1","Point 2","Point 3"]}]},
{"topic":"Week 2: ","subtopics":[{"name":"Title","fullname":"Title title","audio":"2-1.mp3","img":"2-1.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"2-2.mp3","img":"2-2.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"2-3.mp3","img":"2-3.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"2-4.mp3","img":"2-4.jpg","points":["Point 1","Point 2","Point 3"]}]},
{"topic":"Week 3: ","subtopics":[{"name":"Title","fullname":"Title title","audio":"3-1.mp3","img":"3-1.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"3-2.mp3","img":"3-2.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"3-3.mp3","img":"3-3.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"3-4.mp3","img":"3-4.jpg","points":["Point 1","Point 2","Point 3"]}]},
{"topic":"Week 4: ","subtopics":[{"name":"Title","fullname":"Title title","audio":"4-1.mp3","img":"4-1.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"4-2.mp3","img":"4-2.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"4-3.mp3","img":"4-3.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"4-4.mp3","img":"4-4.jpg","points":["Point 1","Point 2","Point 3"]}]},
{"topic":"Week 5: ","subtopics":[{"name":"Title","fullname":"Title title","audio":"5-1.mp3","img":"5-1.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"5-2.mp3","img":"5-2.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"5-3.mp3","img":"5-3.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"5-4.mp3","img":"5-4.jpg","points":["Point 1","Point 2","Point 3"]}]},
{"topic":"Week 6: ","subtopics":[{"name":"Title","fullname":"Title title","audio":"6-1.mp3","img":"6-1.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"6-2.mp3","img":"6-2.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"6-3.mp3","img":"6-3.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"6-4.mp3","img":"6-4.jpg","points":["Point 1","Point 2","Point 3"]}]},
{"topic":"Week 7: ","subtopics":[{"name":"Title","fullname":"Title title","audio":"7-1.mp3","img":"7-1.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"7-2.mp3","img":"7-2.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"7-3.mp3","img":"7-3.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"7-4.mp3","img":"7-4.jpg","points":["Point 1","Point 2","Point 3"]}]},
{"topic":"Week 8: ","subtopics":[{"name":"Title","fullname":"Title title","audio":"8-1.mp3","img":"8-1.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"8-2.mp3","img":"8-2.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"8-3.mp3","img":"8-3.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"8-4.mp3","img":"8-4.jpg","points":["Point 1","Point 2","Point 3"]}]},
{"topic":"Week 9: ","subtopics":[{"name":"Title","fullname":"Title title","audio":"9-1.mp3","img":"9-1.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"9-2.mp3","img":"9-2.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"9-3.mp3","img":"9-3.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"9-4.mp3","img":"9-4.jpg","points":["Point 1","Point 2","Point 3"]}]},
{"topic":"Week 10: ","subtopics":[{"name":"Title","fullname":"Title title","audio":"10-1.mp3","img":"10-1.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"10-2.mp3","img":"10-2.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"10-3.mp3","img":"10-3.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"10-4.mp3","img":"10-4.jpg","points":["Point 1","Point 2","Point 3"]}]},
{"topic":"Week 11: ","subtopics":[{"name":"Title","fullname":"Title title","audio":"11-1.mp3","img":"11-1.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"11-2.mp3","img":"11-2.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"11-3.mp3","img":"11-3.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"11-4.mp3","img":"11-4.jpg","points":["Point 1","Point 2","Point 3"]}]},
{"topic":"Week 12: ","subtopics":[{"name":"Title","fullname":"Title title","audio":"12-1.mp3","img":"12-1.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"12-2.mp3","img":"12-2.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"12-3.mp3","img":"12-3.jpg","points":["Point 1","Point 2","Point 3"]},
{"name":"Title","fullname":"Title title","audio":"12-4.mp3","img":"12-4.jpg","points":["Point 1","Point 2","Point 3"]}]}
];
